workspace:
  base: /go
  path: src/github.com/udistrital/${DRONE_REPO##udistrital/}
  when:
      branch:
      - master
      - release/*
kind: pipeline
name: cliente_deploy

steps:
  # build and test the go program
  - name: nodejs
    image: node:latest
    commands:
     - npm install -g @angular/cli
     - npm i --force
     - ng build --configuration=test
    when:
      branch: [release/*]
      event: [push]

  - name: nodejs_prod
    image: node:latest
    commands:
      - npm install -g @angular/cli
      - npm i --force
      - ng build --configuration=production
    when:
      branch: [master]
      event: [push, pull_request]

  - name: publish_s3
    image: plugins/s3
    settings:
      access_key:
        from_secret: aws_access_key_id
      secret_key:
        from_secret: aws_secret_access_key
      region: "us-east-1"
      bucket: "cliente-pruebas"
      source: www/**/*
      target: /${DRONE_REPO_NAME}
      strip_prefix: www/
    when:
      branch: [release/*]
      event: [push, pull_request]

  - name: publish_s3_prod
    image: plugins/s3
    settings:
      access_key:
        from_secret: aws_access_key_id
      secret_key:
        from_secret: aws_secret_access_key
      region: "us-east-1"
      bucket: "cliente-prod"
      source: www/**/*
      target: /${DRONE_REPO_NAME}
      strip_prefix: www/
    when:
      branch: [master]
      event: [push, pull_request]
