/**
 * @license
 * Copyright Akveo. All Rights Reserved.
 * Licensed under the MIT License. See License.txt in the project root for license information.
 */
export const environment = {
  production: false,
  NUXEO: {
    PATH: 'https://documental.udistrital.edu.co/nuxeo/',
  },
  CLIENTE_PRESUPUESTO: '/pages/plan-cuentas',
  CLIENTE_CONTABILIDAD: 'https://pruebascontabilidad.portaloas.udistrital.edu.co/pages',
  WSO2_SERVICE: 'https://autenticacion.portaloas.udistrital.edu.co/apioas/',
  NECESIDADES_CRUD_SERVICE: 'http://pruebasapi.intranetoas.udistrital.edu.co:8201/v1/',
  PLAN_ADQUISICION_SERVICE: 'https://autenticacion.portaloas.udistrital.edu.co/apioas/bodega_jbpm/v1/',
  // MOVIMIENTOS_CRUD_SERVICE: 'http://localhost:8085/v1/',
  ADMINISTRATIVA_PRUEBAS_SERVICE: 'http://pruebasapi.intranetoas.udistrital.edu.co:8104/v1/',
  // PLAN_CUENTAS_MID_SERVICE: 'http://localhost:8084/v1/',
  // PLAN_CUENTAS_MONGO_SERVICE: 'http://localhost:8082/v1/',
  PLAN_CUENTAS_MONGO_SERVICE: 'http://pruebasapi.intranetoas.udistrital.edu.co:8203/v1/',
  PLAN_CUENTAS_MID_SERVICE: 'http://pruebasapi.intranetoas.udistrital.edu.co:8204/v1/',
  ADMINISTRATIVA_SERVICE: 'http://pruebasapi.intranetoas.udistrital.edu.co:8090/v1/',
  ADMINISTRATIVA_JBPM_SERVICE: 'https://autenticacion.portaloas.udistrital.edu.co/apioas/administrativa_jbpm/v1/',
  // NECESIDADES_CRUD_SERVICE: 'https://autenticacion.udistrital.edu.co/apioas/necesidades_crud/v1/',
  // MOVIMIENTOS_CRUD_SERVICE: 'https://autenticacion.portaloas.udistrital.edu.co/apioas/movimientos_crud/v1/',
  // MOVIMIENTOS_CRUD_SERVICE: 'http://localhost:8085/v1/',
  MOVIMIENTOS_CRUD_SERVICE: 'http://pruebasapi.intranetoas.udistrital.edu.co:8202/v1/',
  // MOVIMIENTOS_CRUD_SERVICE: 'https://autenticacion.udistrital.edu.co/apioas/movimientos_crud/v1/',
  // ADMINISTRATIVA_SERVICE: 'http://pruebasapi.intranetoas.udistrital.edu.co:8201/v1/',
  OIKOS_SERVICE: 'https://autenticacion.portaloas.udistrital.edu.co/apioas/oikos_crud_api/v2/',
  CORE_SERVICE: 'http://pruebasapi.intranetoas.udistrital.edu.co:8092/v1/',
  CORE_AMAZON_SERVICE: 'https://autenticacion.portaloas.udistrital.edu.co/apioas/core_amazon_crud/v1/',
  CONFIGURACION_SERVICE: 'https://autenticacion.portaloas.udistrital.edu.co/apioas/configuracion_crud_api/v1/',
  CONF_MENU_SERVICE: 'https://autenticacion.portaloas.udistrital.edu.co/apioas/configuracion_crud_api/v1/menu_opcion_padre/ArbolMenus/',
  KNOWAGE: {
    PROTOCOL: 'https',
    HOST: 'tuleap.udistrital.edu.co',
    PORT: '',
    CONTEXTPATH: 'knowage',
    USER: 'bidev',
    PASSWORD: 'bidev',
  },
  MAPSKEY: 'AIzaSyB_TBcoCJNaFCJBiwMreM2PoHOkj19Gr00',
  TOKEN: {
    AUTORIZATION_URL: 'https://autenticacion.portaloas.udistrital.edu.co/oauth2/authorize',
    CLIENTE_ID: 'e36v1MPQk2jbz9KM4SmKhk8Cyw0a', // s2BR5hCyo1Bea2dCiMxx9usviQoa -
    RESPONSE_TYPE: 'id_token token',
    SCOPE: 'openid email role',
    REDIRECT_URL: 'http://localhost:4200/',
    SIGN_OUT_URL: 'https://autenticacion.portaloas.udistrital.edu.co/oidc/logout',
    SIGN_OUT_REDIRECT_URL: 'http://localhost:4200/',
  },
  API_GET_IDENTIFICATION: 'https://autenticacion.portaloas.udistrital.edu.co/apioas/autenticacion_mid/v1/token/userRol',
  DATOS_IDENTIFICACION_TERCERO_ENDPOINT: 'https://autenticacion.portaloas.udistrital.edu.co/apioas/terceros_crud/v1/datos_identificacion',

  // OVARGAS
  TERCEROS_SERVICE: 'https://autenticacion.portaloas.udistrital.edu.co/apioas/terceros_crud/v1',
  INFO_COMPLEMENTARIA_IDS: {
    ESTADO_CIVIL: [8, 9, 10, 11, 12], // 32 -> F, 33 -> M, 34 -> no aplica, 
    GENERO: [32, 33, 34], // 32 -> F, 33 -> M, 34 -> no aplica, 
    CELULAR: 52,
    CORREO_PERSONAL: 53, // o 253
    DIRECCION: 54,
    RED_SOCIAL_UNO: 254,
    RED_SOCIAL_DOS: 255,
    NACIONALIDAD: 252,
    LUGAR_NACIMIENTO: 250,
    ESTRATO: [159, 160, 161, 162, 163, 164, 165],
    NOMBRE_COLEGIO: 259,
    CIUDAD_COLEGIO: 260,
    FECHA_GRADUACION: 261,
    INTERESES: 320,
    PAIS_RESIDENCIA: 321,
    DEPARTAMENTO_RESIDENCIA: 323,
    CODIGO_PAIS: 324,
    MUNICIPIOS: [147, 148, 149],


    CODIGO_DEL_PAS: 1248,
    PAISES: 1249,
    DEPARTAMENTOS: 1250,
    TIPO_DE_POBLACION: 1251,
    CONDICIONES_DISCAPACIDAD: 1252,
    NOMBRE_DE_SU_EMPRESA: 1253,
    NIT_DE_LA_EMPRESA: 1254,
    SECTOR_ECONOMICO_DE_LA_EMPRESA: 1255,
    SITIO_WEB_DE_LA_EMPRESA: 1256,
    FECHA_DE_FUNDACION_DE_LA_EMPRESA: 1257,
    ACTIVIDADES_QUE_REALIZA_LA_EMPRESA: 1258,
    NECESIDADES_PROFESIONALES_SATISFACCION: 1259,
    NECESIDADES_ECONOMICAS_SATISFACCION: 1260,
    NECESIDADES_DESARROLLO_PERSONAL_SATISFACCION: 1261,
    NECESIDADES_CON_SU_EMPRESA_SATISFACCION: 1262,
    CANTIDAD_DE_EMPLEADOS: 1263,
    CANTIDAD_DE_PROFESIONALES_O_TECNOLOGOS_EMPLEADOS: 1264,
    CANTIDAD_DE_EGRESADOS_DE_LA_UD_PROFESIONALES_O_TECNOLOGOS_EMPLEADOS: 1265,
    CANTIDAD_DE_EMPLEOS_OPERATIVOS_ASISTENCIALES_O_DE_APOYO_GENERADOS: 1266,
    PRINCIPAL_DIFICULTAD_A_LA_HORA_DE_CONSEGUIR_TRABAJO: 1267,
    CANAL_DE_BUSQUEDA_DE_EMPLEO: 1268,
    PROBLEMTICAS_EN_DONDE_CONSIDERA_QUE_HA_APORTADO: 1269,
    OTRA_PROBLEMTICA_EN_DONDE_CONSIDERA_QUE_HA_APORTADO: 1270,
    PROGRAMAS_DE_POSGRADO_TITULADOS_EN_LA_UD: 1271,
    SITUACION_LABORAL: 1272,
    CUNTO_TIEMPO_EN_MESES_LLEVA_EN_ESTA_ACTIVIDAD_O_TRABAJO: 1273,
    INGRESO_O_SALARIO_SATISFACCION_LABORAL: 1274,
    CANTIDAD_DE_HORAS_SATISFACCION_LABORAL: 1275,
    APLICACION_DE_CONOCIMIENTOS_DE_LA_CARRERA__SATISFACCION_LABORAL: 1276,
    RETOS_Y_DESAFOS_INTELECTUALES_SATISFACCION_LABORAL: 1277,
    OPORTUNIDADES_DE_ASCENSO_SATISFACCION_LABORAL: 1278,
    ESTABILIDAD_SATISFACCION_LABORAL: 1279,
    INGRESO_O_SALARIO: 1280,
    RAZON_DE_VINCULACION: 1281,
    OTRA_RAZON_DE_VINCULACION: 1282,
    ESTATUS_LABORAL: 1283,
    ACTIVIDADES_QUE_REALIZA: 1284,
    TIPO_DE_CONTRATO: 1285,
    SECTOR: 1286,
    GRUPO_DE_ACTIVIDAD_ECONOMICA: 1287,
    FORMAS_DE_TRABAJO_INDEPENDIENTES: 1288,
    NOMBRE_DE_LA_EMPRESA_EN_DONDE_LABORA: 1289,
    NOMBRE_DE_LA_EMPRESA: 1290,
    CUALES_SON_LOS_PRODUCTOS_O_SERVICIOS: 1291,
    CIUDAD_MUNICIPIO__PROVINCIA_DE_UBICACION_DE_LA_EMPRESA: 1292,
    OPERACION_DE_LA_EMPRESA: 1293,
    ETAPA_EN_QUE_SE_ENCUETRA_LA_EMPRESA: 1294,
    EN_LA_ACTUALIDAD_EN_QU_ACTIVIDAD_OCUPA_LA_MAYOR_PARTE_DE_SU_TIEMPO: 1295,
    DESEA_CONSEGUIR_UN_TRABAJO_O_REALIZAR_UNA_ACTIVIDAD_REMUNERADA: 1296,
    DURANTE_EL_ULTIMO_MES_HIZO_ALGUNA_DILIGENCIA_PARA_CONSEGUIR_UN_TRABAJO_O_REALIZAR_UNA_ACTIVIDAD: 1297,
    AUNQUE_DESEA_TRABAJAR_POR_QU_MOTIVO_NO_HIZO_DILIGENCIAS_PARA_BUSCAR_UN_TRABAJO_EN_EL_ULTIMO_MES: 1298,
    SI_LE_RESULTARA_ALGUN_TRABAJO_REMUNERADO_EST_DISPONIBLE_PARA_EMPEZAR_A_TRABAJAR: 1299,
    HACE_CUNTOS_MESES_HA_ESTADO_BUSCANDO_EMPLEO: 1300,
    SI_DESEA_COMENTARNOS_MS_A_DETALLE_ACERCA_DE_SUS_APORTES_CONTRIBUCIONES_O_LOGROS_PUEDE_HACERLO: 1301,
  },
  GRUPO_INFO_COMPLEMENTARIA_IDS: {
    MUNICIPIOS: 30,
    LOCALIDADES: 29,
    ACADEMICA: 17,
    GENERO: 6,
    INFO_CONTACTO: 10,
    ESTADO_CIVIL: 2,
  },
  API_ENDPOINT_UBICACIONES: "https://autenticacion.portaloas.udistrital.edu.co/apioas/ubicaciones_crud/v2/",
  EVENTOS_ENDPOINT: "https://autenticacion.portaloas.udistrital.edu.co/apioas/sesiones_crud/v2",
  OIKOS_POSGRADOS_ID: 15,
};
